### ISSUE TITLE
The terminal process terminated with exit code: -3

### ISSUE THREAD

**Issue by laibulle** [microsoft/vscode-dev-containers#110]
- VSCode Version: 1.37.0-insider
- Local OS Version: OSX mojave 10.14.5 (18F203)
- Name of Dev Container Definition with Issue:

Steps to Reproduce:

1. Create a Dockerfile
```
FROM elixir:1.7-alpine

RUN apk update && \
    apk --no-cache --update add \
    git make g++ wget curl inotify-tools build-base

RUN apk add --no-cache \
    bash gawk sed grep coreutils

RUN apk add --no-cache \
    imagemagick

RUN apk add nodejs nodejs-npm && \
        npm install npm -g --no-progress && \
        update-ca-certificates --fresh && \
        rm -rf /var/cache/apk/*

RUN mkdir /app \
    && chmod -R 777 /app

WORKDIR /app

RUN mix local.rebar --force \
    && mix local.hex --force \
    && mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez --force
```
2 - Create a docker-compose.yml

```
version: "3"
services:
    phoenix:
        build: ./
        ports:
            - "4000:4000"
- "4000:4000"
- "4000:4000"
        volumes:
            - ./:/app:delegated
        working_dir: /app
        command: /bin/sh -c "mix deps.get && mix phx.server"
        networks:
          - devtools_net

volumes:
  elixir-artifacts: {}    

networks:
    devtools_net:
        external: true

```

<img width="1110" alt="Screenshot 2019-07-31 at 00 48 53" src="https://user-images.githubusercontent.com/2327626/62171166-56f0cd00-b32e-11e9-9de3-05ad34ccefe2.png">
