### ISSUE TITLE
Minikube in docker: exposing ingress to localhost

### ISSUE THREAD

**Issue by mr-bjerre** [microsoft/vscode-dev-containers#1107]
Relates to: Remote - Containers

I am using the neatly prepared [minikube in docker remote container](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/kubernetes-helm-minikube). It works really good and I have everything up and running. I use nginx ingress controller so I have something like this

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-controller
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /upload
spec:
  rules:
    - host: pub.local
      http:
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: upload
                port: 
                  number: 80
```

If I do `minikube ip` then I have `192.168.49.2`. So if I add the following line to `/etc/hosts` in my devcontainer then I can access my `upload` service using `pub.local` dns.

```
192.168.49.2 pub.local
```

Now I'd like to do this outside of the devcontainer so I figured I need to port forward 192.168.49:80 to 127.0.0.1:80 or something like that but how do I do that?

I've tried

```
/usr/bin/docker-proxy -proto tcp -host-ip 127.0.0.1 -host-port 80 -container-ip 192.168.49.2 -container-port 80
```

but that gives me `Stopping proxy on tcp/127.0.0.1:80 for tcp/192.168.49.2:80 (accept tcp4 127.0.0.1:80: accept4: bad file descriptor)`
