### ISSUE TITLE
Example Issue: Docker-Compose Network

### ISSUE THREAD

**Issue by rorychatterton** [microsoft/vscode-dev-containers#1743]
In the example for docker-compose, the use of `network_mode` is used.

By using this feature, SSHD forwarding (which is required for IntelliJ or the Github CLI to work) does not work properly, remaining stuck in a loop. Tis feature is defined here:

https://github.com/microsoft/vscode-dev-containers/blob/5a084a93b0736ea86395ac99019a5b72a00b6341/container-templates/docker-compose/.devcontainer/docker-compose.yml#L24

Removing this line allows SSHD to forward and fixes this issue.

It is not required for port forwarding using devcontainer json syntax, and inter-connectivity works properly  by using the `<service_name>:<port>` syntax (e.g. `db:5432`) in the connection string.

Example Configuration:
```yml
version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/java:17
    volumes:
      - ../..:/workspaces:cached
    command: /bin/sh -c "while sleep 1000; do :; done"  

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data:
```

Example working Dev Container -> Postgres Container through the Postgres plugin for VsCode.
<img width="407" alt="Screenshot 2023-05-18 at 4 57 36 pm" src="https://github.com/microsoft/vscode-dev-containers/assets/11748379/bcc76b0f-1424-4483-9ee6-a0f467272de1">

Example devcontainer app forwarding:
<img width="1269" alt="Screenshot 2023-05-18 at 5 22 53 pm" src="https://github.com/microsoft/vscode-dev-containers/assets/11748379/aca60f74-acc6-4821-95f3-5ab5271dec9e">
