### ISSUE TITLE
docker-compose - [VS Online] Process finished successfully.

### ISSUE THREAD

**Issue by extravio** [microsoft/vscode-dev-containers#219]
I'm trying to set up a LAMP stack on VS online.

If I follow the example "vscode-remote-try-php"
https://github.com/microsoft/vscode-remote-try-php/tree/master/.devcontainer
and replace the php:7-cli image by php/7.3-apache image (https://hub.docker.com/_/php) 
the container starts and I can connect to it.
I need to start the apache service **manually** though (the process should be running by default as it does when running the container locally). 

However, if I try to use docker-compose, the process in the container finishes after the environment is created an I can connect to it and use the apache server. 
The output on the command line is:
`[VS Online][df260505-a84d-4e69-a10c-ac01a86b6261] Process finished successfully.`

I used the templates here:
https://github.com/microsoft/vscode-dev-containers/tree/master/container-templates/docker-compose/.devcontainer

Here my docker-compose.yml
```
version: "3"
services:
  php73:
    user: vscode
    image: php/7.3-apache
    ports:
      - "80:80"
    volumes:
      - ..:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
```

I've tried modifying the "command" by "sudo service apache2 start"
or execute this command in the "postCreateCommand" of my devcontainer.json without success.

It looks like there's something wrong with the "Overrides default command so things don't shut down after the process ends".

Expected behaviour: if there no  "command" entry in the docker-compose.yml file, the native process (in my case: the apache service) should be running.
