### ISSUE TITLE
Wrong build context path in existing container template

### ISSUE THREAD

**Issue by holms** [microsoft/vscode-dev-containers#280]
- **VSCode Version**:
```
holms@debian ~/D/c/s/app-prebid-config> code-insiders --version
1.44.0-insider
2aae1f26c72891c399f860409176fe435a154b13
x64
```

- **Local OS Version:** Debian latest
- **Name of Dev Container Definition with Issue:** go

Steps to Reproduce:

1. Create custom Dockerfile in `.devcontainer` folder.
2. Uncomment step   which says `context: .` in `.devcontainer/docker-compose.yml` https://github.com/microsoft/vscode-dev-containers/blob/bf82fa0128cec15e935d04bbb50761e45a907f37/containers/docker-existing-docker-compose/.devcontainer/docker-compose.yml#L18-L21
3. Launch `docker-compose -f docker-compose.yml -f .devcontainer/docker-compose.yml build` 
3. See the world burn: ```ERROR: Cannot locate specified Dockerfile: Dockerfile```

This seems to be a bug in a docker-compose. I've already registered in here: https://github.com/docker/compose/issues/7350

I'm not sure is this indented behavior, or not. What is happening is that if you'd do `docker-compose -f docker-compose.yml -f .devcontainer/docker-compose.yml config` you'd see build context showing to a folder where `docker-compose.yml` is located, although in my opinion context should point to CWD of the config which overrides previous one. I'm pretty sure you've though it's using CWD (or maybe it was working this way before).
This is an issue on RC and also latest stable release. So if I use your provided `build context: .` this won't work, `Dockerfile` won't be found, you need to put  into build context this:`./.devcontainer/`,  then it works fine.

Here's first config `docker-compose.yml`

```
 app-prebid-config:
        container_name: app-prebid-config
        build:
            context: app 
            dockerfile: Dockerfile
        volumes:
            - ./app:/app/prebid-config

```
Here's `.devcontainer/docker-compose.yml`

```
version: '3.7'
services:
    app-prebid-config:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./app:/workspace:cached
        cap_add:
            - SYS_PTRACE
        security_opt:
            - seccomp:unconfined
        command: /bin/sh -c "while sleep 1000; do:; done"

```

Now let's see what config command shows:

```
$ docker-compose  --project-name app-prebid-config -f docker-compose.yml -f .devcontainer/docker-compose.extend.yml  config
....
  app-prebid-config:
    build:
      context: /home/holms/Dev/contracts/setupad/app-prebid-config
      dockerfile: Dockerfile
...
```

And of course the build would fail:
```
holms@debian ~/D/c/s/app-prebid-config> docker-compose  --project-name app-prebid-config -f docker-compose.yml -f .devcontainer/docker-compose.extend.yml  build
Building app-prebid-config
ERROR: Cannot locate specified Dockerfile: Dockerfile
```

As no Dockerfile exist near `docker-compose.yml`. And I believe anyone would want to use `.devcontainer/Dockerfile` in the first place in your overriden docker-compose config, as it contains all custom tools for debuging golang specifically for vscode.  In docker-compose.yml I'm using default Dockerfile location which is a Dockerfile for CI only, and checking it it's builds locally is quite healthy for a developer I believe after coding job is done, at least checking does it compile on a build stage is extremely useful.

Also created this issue in release https://github.com/microsoft/vscode-remote-release/issues/2681  but I'm not sure if it's their fault, it's this template fault or docker-compose itself. 
This btw might be related: https://github.com/microsoft/vscode-dev-containers/issues/247
