### ISSUE TITLE
Kubernetes missing certificate

### ISSUE THREAD

**Issue by Shikanime** [microsoft/vscode-dev-containers#33]
- VSCode Version: 1.34.0-insider (1.34.0-insider)
- Local OS Version: macOS Mojare 10.14.4 (18E226)
- Name of Dev Container Definition with Issue: Kubernetes & Helm

Steps to Reproduce:

1. Click on "Reopen on Container"
2. New terminal

Context:

Minikube certificates are not pull and paths are not replaced in the kube configuration.

```
- name: minikube
  user:
    client-certificate: /Users/USER_NAME/.minikube/client.crt
    client-key: /Users/USER_NAME/.minikube/client.key
```
