### ISSUE TITLE
Cannot connect to postgres

### ISSUE THREAD

**Issue by olaven** [microsoft/vscode-dev-containers#369]
Hi! Thanks for this amazing piece of technology. 
I am starting a devcontainer with node and postgres, based on the example provided here. 
However, I am not able to connect to the database from the node program. 
Exposing the port, i _am_ able to connect with a postgres client on my mac (pgadmin 4)

- VSCode Version: 1.47.0-insider
- Local OS Version: 10.15.3 

## files 
```json 
{
	"name": "development",
	"dockerComposeFile": "docker-compose.yml",
	"service": "web",
	"workspaceFolder": "/workspace",
	"forwardPorts": [
		3000,
		5432
	],
	"postCreateCommand": "yarn install",
	"settings": {
		"terminal.integrated.shell.linux": "/bin/bash"
	},
	"extensions": [
		"dbaeumer.vscode-eslint",
		"firefox-devtools.vscode-firefox-debug"
	],
}
```
```yml
#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

  version: '3'
  services:
    web:
      image: node:12 
      volumes:
        - ..:/workspace:cached
        
      # Overrides default command so things don't shut down after the process ends.
      command: sleep infinity
  
      links:
        - db
  
    db:
      image: postgres
      restart: unless-stopped
      ports: 
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: pass
        POSTGRES_USER: user
        POSTGRES_DB: data
```
```
#.env 
PGUSER=user
PGPASSWORD=pass
PGDATABASE=data
```
```ts
//Trying to pass config manually
const pgPool = new Pool({ 
    user: 'user',
    database: 'data',
    password: 'pass',
});
// Should pick up from .env 
const pgPool = new Pool();
```
The error: 
`connect ECONNREFUSED 127.0.0.1:5432`

Steps to Reproduce:

1. Setup devcontainer with config files like above
2. Try to connect with `node-postgres`

__EDIT__ I have also tried with exactly the same config files as the postgres + node example provides :-)
