### ISSUE TITLE
Swap out the api-server URL to host.docker.internal got mistakes.

### ISSUE THREAD

**Issue by Aisuko** [microsoft/vscode-dev-containers#442]
- VSCode Version:

```
Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:18:50.054Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0
```

- Local OS Version: macOS Catalina

- Name of Dev Container Definition with Issue: kubernetes-helm

Steps to Reproduce:

1. Executing the `minikube start ` or `kind create cluster` command on macOS and docker context use local macOS docker daemon
2. Open the project includes the `kubernetes-helm` and run command `kubectl config view`

```
root@48d627aa382f:/workspaces/meshery-linkerd# kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /root/.minikube/ca.crt
    server: https://127.0.0.1:32772
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /root/.minikube/client.crt
    client-key: /root/.minikube/client.key
```

**Should change to **

```
root@48d627aa382f:/workspaces/meshery-linkerd# kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /root/.minikube/ca.crt
    server: https://host.docker.internal:32772
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /root/.minikube/client.crt
    client-key: /root/.minikube/client.key
```
