### ISSUE TITLE
Unable to connect to the server: certificate is not  valid for host.docker.internal

### ISSUE THREAD

**Issue by Aisuko** [microsoft/vscode-dev-containers#449]
- VSCode Version:
```
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:08:29.692Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0
```
- Local OS Version:
   macOS Catalina
- Name of Dev Container Definition with Issue: Kubernetes & Helm 

Steps to Reproduce:

1. mount the `/.kube` and `/.minikube` folder into the container and run the command with `kubectl`

```
root@0ab3a3828ae9:/workspaces/meshery-linkerd# kubectl cluster-info

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: x509: certificate is valid for minikubeCA, control-plane.minikube.internal, kubernetes.default.svc.cluster.local, kubernetes.default.svc, kubernetes.default, kubernetes, localhost, not host.docker.internal

root@0ab3a3828ae9:/workspaces/meshery-linkerd# kubectl cluster-info --insecure-skip-tls-verify
Kubernetes master is running at https://host.docker.internal:32772
KubeDNS is running at https://host.docker.internal:32772/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
root@0ab3a3828ae9:/workspaces/meshery-linkerd# kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /root/.minikube/ca.crt
    server: https://host.docker.internal:32772
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /root/.minikube/client.crt
    client-key: /root/.minikube/client.key
```

**The same issue I hit on `kubernetes/Kind`(macOS local executing `kind create cluster` and try to communicate the cluster in the (1kubernetes&helm1 which same host different container) and `kind get kubeconfig --name kind --internal` useless for me)**
