### ISSUE TITLE
[docker-from-docker-compose] - Volume mounting inside the container not working as expected

### ISSUE THREAD

**Issue by Divlo** [microsoft/vscode-dev-containers#592]
- VSCode Version: 1.49.2
- Local OS Version: Ubuntu 20.04.1 LTS
- Name of Dev Container Definition with Issue: docker-from-docker-compose

My goal is to use docker-from-docker-compose with multiple node.js app I can start with a simple `docker-compose up` inside a VSCode remote container. There is no problem about that, but what I want is to have "hot reload" with nodemon (so I create volumes), here is my `docker-compose.yml` file :

```yml
version: '3.0'
services:
  app:
    build:
      context: './app'
    volumes:
      - ./app:/app-typescript/app
      - /app-typescript/app/node_modules
    container_name: 'app'
```

And here is my Dockerfile in the `app` folder : 
```Dockerfile
FROM node:12.18.4-alpine3.12

WORKDIR /app-typescript

COPY ./package*.json ./
RUN npm install
COPY ./ ./

CMD npm run dev
```

My `.dockerignore` file in the `app` folder : 
```
node_modules
build
.vscode
```

But when I start with `docker-compose up --build`, npm can't find the package.json files : `npm ERR! enoent ENOENT: no such file or directory, open '/app-typescript/package.json'`, if I remove the two lines in the `docker-compose.yml` that create the volumes my app is starting with no problem but I can't have the hot reload.

Note: It is working if I start `docker-compose up --build` locally (outside the container, directly in the folder), I have everything working as expected.

I don't think it's a issue on my side since it is working outside a developement container, that's why I open a issue instead of a stackoverflow question.

Also I would like more explanation about the `.devcontainer/docker-compose.yml` : 
```yml
version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: 999
        USER_GID: 999
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock 
      - ..:/workspace:cached
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity 
```

What does this line exactly do : `- /var/run/docker.sock:/var/run/docker-host.sock `
And what is the problem with USER_UID and USER_GID on Linux ? 

I really can't find out my issue since yesterday, I would be really glad if someone can help me, thank you for your help,

**Comment by Chuxel** [comment]
You can find out more about configuring docker compose in docs: https://code.visualstudio.com/docs/remote/create-dev-container#_use-docker-compose

User UID/GID is referenced from there and provides an explanation:  https://aka.ms/vscode-remote/containers/non-root

The docker-host is described the readme for the definition: https://github.com/microsoft/vscode-dev-containers/tree/master/containers/docker-from-docker-compose

For your Dockerfile, I'd try just using the docker CLI - it sounds like there's something potentially wrong with it - I'd also verify your 'context' value is actually correct.

**Comment by Divlo** [comment]
Thank you for your help @Chuxel.
I see better what is the USER_UID/GID.
But I think you misunderstood the issue.

Basically what I want is to have access to `docker-compose` inside my VSCode remote container. What I understood from the docs is that I can use the [https://aka.ms/vscode-remote/samples/docker-from-docker-compose](Docker-from-Docker Compose) dev container définition example.
So what I did is to copy this example and I edited the `Dockerfile` and `docker-compose yml` with my service I wanted to start
As I said my `docker-compose.yml` and `Dockerfile` is working outside the container (I'm talking about the Dockerfile/docker-compose.yml files for the application not for the dev container).

I'll have again a further look this weekend , maybe I can create a reproductible GitHub repo so you can see the issue, what do you think.

**Comment by Chuxel** [comment]
Yeah that may be due to a different issue - which is that bind mounts are going to be tied to the host OS, not the container. 

There's a trick to use an env var for this: https://github.com/microsoft/vscode-dev-containers/tree/master/containers/docker-from-docker-compose#using-bind-mounts-when-working-with-docker-inside-the-container

**Comment by Divlo** [comment]
Yes that was the issue, I didn't know I could use variables environments inside my `docker-compose.yml` file.
Everything is now working as expected, here is my new `docker-compose.yml` file :
```yml
version: '3.0'
services:
  app:
    build:
      context: './app'
    volumes:
      - '${LOCAL_WORKSPACE_FOLDER:-.}/app:/app-typescript/app'
      - '/app/node_modules'
    container_name: 'app'
```
Thanks for your help, I close the issue.
