### ISSUE TITLE
Docker Compose containers cannot communicate in GitHub Codespaces due to host networking being applied to only one container

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-dev-containers#637]
For Docker Compose definitions, there is an upstream bug in GitHub Codespaces that forces the main container into `network_mode: host` without also changing the related containers to the same networking mode.

The net effect is that the the different Compose managed containers can't communicate.  The GitHub Codespaces team is working on a fix.

In the mean time you can work around it by adding `network_mode: host` to each service. This should work both locally and in Codespaces.

e.g. For [Node + MongoDB](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/javascript-node-mongo):

```yaml
version: '3'

services:
  app:
    # *** UPDATED - used to be network_mode: service:db****
    network_mode: host

    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # [Choice] Node.js version: 14, 12, 10
        VARIANT: 14
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity


    # Uncomment the next line to use a non-root user for all processes.
    # user: node

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    # ***ADDED****
    network_mode: host

    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db

    # Uncomment to change startup options
    # environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    #  MONGO_INITDB_DATABASE: your-database-here

    # Add "forwardPorts": ["27017"] to **devcontainer.json** to forward MongoDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  mongodb-data:
```

This affects:
