### ISSUE TITLE
javascript-node-mongo devcontainer rebuild fails

### ISSUE THREAD

**Issue by sevspo** [microsoft/vscode-dev-containers#805]
- VSCode Version: 1.55.0
- Local OS Version: Windows 10 2004
- WSL Ubuntu 20.04
- Docker v20.10.5
- Name of Dev Container Definition with Issue: javascript-node-mongo

### Steps to Reproduce:

1. Remote-Containers: Rebuild an Reopen in Container

### Error Log:
```
[2021-04-01T08:07:54.129Z] [PID 12348] 
[+] Building 4.6s (5/6)
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 38B                                        0.0s
 => [internal] load .dockerignore                                          0.1s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for mcr.microsoft.com/vscode/devcontainers/j  0.0s
 => CACHED [1/3] FROM mcr.microsoft.com/vscode/devcontainers/javascript-n  0.0s
 => ERROR [2/3] RUN curl -sSL "https://www.mongodb.org/static/pgp/server-  4.4s
------
 > [2/3] RUN curl -sSL "https://www.mongodb.org/static/pgp/server-4.2.asc" | (OU
T=$(apt-key add - 2>&1) || echo $OUT)     && echo "deb http://repo.mongodb.org/a
pt/debian $(lsb_release -cs)/mongodb-org/4.2 main" | tee /etc/apt/sources.list.d
/mongodb-org-4.2.list     && apt-get update && export DEBIAN_FRONTEND=noninterac
tive     && apt-get install -y mongodb-org-tools mongodb-org-shell     && apt-ge
t clean -y && rm -rf /var/lib/apt/lists/*:
#4 1.383 deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.2 main
#4 1.566 Get:1 http://deb.debian.org/debian buster InRelease [121 kB]
#4 1.568 Get:2 http://security.debian.org/debian-security buster/updates InRelea
se [65.4 kB]
#4 1.573 Get:3 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
#4 1.669 Get:4 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
#4 1.706 Err:3 https://dl.yarnpkg.com/debian stable InRelease
#4 1.706   The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yar
n Packaging <yarn@dan.cx>
#4 1.766 Ign:5 http://repo.mongodb.org/apt/debian buster/mongodb-org/4.2 InRelea
se
#4 1.793 Get:6 http://repo.mongodb.org/apt/debian buster/mongodb-org/4.2 Release
 [1488 B]
#4 1.852 Get:7 http://security.debian.org/debian-security buster/updates/main am
d64 Packages [269 kB]
#4 1.931 Get:8 http://repo.mongodb.org/apt/debian buster/mongodb-org/4.2 Release
.gpg [801 B]
#4 2.003 Get:9 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
#4 2.513 Get:10 http://repo.mongodb.org/apt/debian buster/mongodb-org/4.2/main a
md64 Packages [10.9 kB]
#4 2.728 Get:11 http://deb.debian.org/debian buster-updates/main amd64 Packages
[9504 B]
#4 3.731 Reading package lists...
#4 4.308 W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The follo
wing signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@da
n.cx>
#4 4.308 E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is n
ot signed.
------
executor failed running [/bin/sh -c curl -sSL "https://www.mongodb.org/static/pg
p/server-${MONGO_TOOLS_VERSION}.asc" | (OUT=$(apt-key add - 2>&1) || echo $OUT)
    && echo "deb http://repo.mongodb.org/apt/debian $(lsb_release -cs)/mongodb-o
rg/${MONGO_TOOLS_VERSION} main" | tee /etc/apt/sources.list.d/mongodb-org-${MONG
O_TOOLS_VERSION}.list     && apt-get update && export DEBIAN_FRONTEND=noninterac
tive     && apt-get install -y mongodb-org-tools mongodb-org-shell     && apt-ge
t clean -y && rm -rf /var/lib/apt/lists/*]: exit code: 100
ERROR: Service 'app' failed to build
```

### docker-compose.yml

```yml
version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # [Choice] Node.js version: 14, 12, 10
        VARIANT: 14
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:mongo

    # Uncomment the next line to use a non-root user for all processes.
    # user: node

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db

    # Uncomment to change startup options
    environment:
      MONGO_INITDB_ROOT_USERNAME: sevi
      MONGO_INITDB_ROOT_PASSWORD: mongobili
    #   MONGO_INITDB_DATABASE: my-api/

    # Add "forwardPorts": ["27017"] to **devcontainer.json** to forward MongoDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  mongodb-data:
```

### devcontainer.json

```jsonc
// For format details, see https://aka.ms/devcontainer.json. For config options, see the README at:
// https://github.com/microsoft/vscode-dev-containers/tree/v0.154.0/containers/javascript-node-mongo
// Update the VARIANT arg in docker-compose.yml to pick a Node.js version: 10, 12, 14
{
  "name": "Node.js & Mongo DB Rest Api",
  "dockerComposeFile": "docker-compose.yml",
  "service": "app",
  "workspaceFolder": "/workspace",

  // Set *default* container specific settings.json values on container create.
  "settings": {
    "terminal.integrated.shell.linux": "/bin/bash"
  },

  // Add the IDs of extensions you want installed when the container is created.
  "extensions": [
    "dbaeumer.vscode-eslint",
    "mongodb.mongodb-vscode",
    "visualstudioexptteam.vscodeintellicode",
    "tabnine.tabnine-vscode",
    "esbenp.prettier-vscode"
  ],

  // Use 'forwardPorts' to make a list of ports inside the container available locally.
  "forwardPorts": [8080, 5555, 5556],

  // Use 'postCreateCommand' to run commands after the container is created.
  // "postCreateCommand": "yarn install",

  // Comment out connect as root instead. More info: https://aka.ms/vscode-remote/containers/non-root.
  "remoteUser": "node"
}
```
